# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-09 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Название новости')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='Publish Date')),
                ('content', models.TextField(verbose_name='Описание')),
                ('news', models.TextField(verbose_name='Новость:')),
                ('img', models.ImageField(upload_to='Albums', verbose_name='Изображение')),
            ],
        ),
    ]
