# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-01 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uslugi_photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название фото-услуги')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Фото-услуга',
                'verbose_name_plural': 'Фото-услуги',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='uslugi_video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название видео-услуги')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Видео-услуга',
                'verbose_name_plural': ['Видео-услуги'],
                'ordering': ['title'],
            },
        ),
    ]
