# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-09 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0002_auto_20170108_2245'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog1',
        ),
    ]
