# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-24 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('photo', models.ImageField(upload_to='Albums', verbose_name='Фотография')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Ваш отзыв')),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Отзыв',
                'ordering': ['date'],
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
