# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-26 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
