# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-30 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_auto_20170130_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='photo',
            field=models.FileField(upload_to='Albums', verbose_name='Фотография'),
        ),
    ]
